### ISSUE TITLE
사이드바 화면 수정해야할 것

### ISSUE THREAD

**Issue by KKonzi** [devSoyoung/whale-extension-keycrab#6]
## 키워드 관련
- [x] 키워드 즐겨찾기 > 키워드 추적 on/off로 변경 (아이콘 고민해보기)
- [x] 키워드에 띄어쓰기 있는 경우 수정하기
- [x] `msg.type === 'UPDATE_KEYWORDS'` 에서 배열의 길이 비교하여 추가되는 경우에만 키워드 추가 함수 작동하도록 수정
- [x] 키워드 말줄임
- [x] 삭제 `confirm`받기
- [x] 접기 버튼 방향 반대로

**Comment by KKonzi** [comment]
## 링크 관련- [ ] 링크의 즐겨찾기 기능 추가
- [x] 줄바꿈을 ... 말줄임으로 바꾸기
- [x] 링크 `favorite` 핀 기능 UI 및 기능 추가하기

**Comment by KKonzi** [comment]
- [x] 저장된 링크 없을 때 최초화면
- [x] 키워드 추가할 때 이름순으로 정렬되있는 append

**Comment by devSoyoung** [comment]
## TODO
- [x] 검색창 검색 아이콘 추가
- [x] 키워드 비어있을 때 메세지 추가
- [ ] 삭제버튼 클릭 시 alert > modal로 수정

**Comment by KKonzi** [comment]
- [x] 키워드 있다가 다 삭제하면 초기화면 사라짐
- [x] 버리기,접기 얇은 아이콘으로 바꾸기
- [ ] 종버튼 추적 동기화
- [x] origin 별로 글자 다르게 하기
- [ ] origin 별로 글자 색 다르게하기
